# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.22
# 
# >> macros
# << macros

Name:       kde5-libksysguard
Summary:    KDE process management library
Version:    5.0.0
Release:    1
Group:      System/Base
License:    GPLv2+
URL:        http://www.kde.org
Source0:    %{name}-%{version}.tar.xz
Source100:  kde5-libksysguard.yaml
Source101:  kde5-libksysguard-rpmlintrc
Requires:   kde5-filesystem
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5DBus)
BuildRequires:  pkgconfig(Qt5Xml)
BuildRequires:  pkgconfig(Qt5Network)
BuildRequires:  pkgconfig(Qt5Gui)
BuildRequires:  pkgconfig(Qt5Widgets)
BuildRequires:  pkgconfig(Qt5Concurrent)
BuildRequires:  pkgconfig(Qt5Test)
BuildRequires:  pkgconfig(Qt5WebKit)
BuildRequires:  pkgconfig(Qt5X11Extras)
BuildRequires:  pkgconfig(Qt5Script)
BuildRequires:  pkgconfig(Qt5WebKitWidgets)
BuildRequires:  pkgconfig(Qt5PrintSupport)
BuildRequires:  kde5-rpm-macros
BuildRequires:  extra-cmake-modules
BuildRequires:  qt5-tools
BuildRequires:  kf5-ki18n-devel
BuildRequires:  kf5-kdelibs4support-devel
BuildRequires:  kf5-plasma-devel
BuildRequires:  kf5-kconfig-devel
BuildRequires:  kf5-knewstuff-devel
BuildRequires:  zlib-devel
BuildRequires:  libXres-devel


%description
KDE process management library



%package devel
Summary:    Development files for %{name}
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}

%description devel
The %{name}-devel package contains the files necessary to develop applications
that use %{name}.



%prep
%setup -q -n %{name}-%{version}/upstream

# >> setup
# << setup

%build
# >> build pre
%kde5_make
# << build pre



# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
%kde5_make_install
# << install pre

# >> install post
# << install post









%files
%defattr(-,root,root,-)
%doc COPYING.LIB
%{_kde5_libdir}/liblsofui.so.*
%{_kde5_libdir}/libprocessui.so.*
%{_kde5_libdir}/libprocesscore.so.*
%{_kde5_libdir}/libksignalplotter.so.*
%{_kde5_libdir}/libksgrd.so.*
%{_kde5_datadir}/ksysguard
# >> files
# << files


%files devel
%defattr(-,root,root,-)
%{_kde5_includedir}/ksysguard
%{_kde5_libdir}/liblsofui.so
%{_kde5_libdir}/libprocessui.so
%{_kde5_libdir}/libprocesscore.so
%{_kde5_libdir}/libksignalplotter.so
%{_kde5_libdir}/libksgrd.so
%{_kde5_libdir}/cmake/KF5SysGuard
# >> files devel
# << files devel

